// <auto-generated />
namespace TiendaVirtual.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProducto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProducto));
        
        string IMigrationMetadata.Id
        {
            get { return "202502031736516_AddProducto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
